### ISSUE TITLE
SAR is displayed when selecting any of the values from discount

### ISSUE THREAD

**Issue by AnjaliVellookkaran** [techgebra/polosys-books#104]
![Screenshot from 2023-06-26 15-01-53](https://github.com/techgebra/polosys-books/assets/131741149/d40dad3b-e867-4862-9a3b-0e9195a5f800)

**Comment by MohdSahal** [comment]
Show discount amount even client choose discount percentage. @MohamedRoshanPU

**Comment by AnjaliVellookkaran** [comment]
this issue is fixed !
