### ISSUE TITLE
not able to manually enter values to amount paid field in bills under purchase module

### ISSUE THREAD

**Issue by AnjaliVellookkaran** [techgebra/polosys-books#106]
- [x] ![Screenshot from 2023-06-26 15-14-38](https://github.com/techgebra/polosys-books/assets/131741149/40c34ef7-5bd1-4ba7-bef6-518d9e7ce981)

**Comment by MohdSahal** [comment]
@AnjaliVellookkaran check and close

**Comment by AnjaliVellookkaran** [comment]
@zahidmuhammed issue not solved yet
zero is still displaying
![Screenshot from 2023-07-05 15-49-44](https://github.com/techgebra/polosys-books/assets/131741149/75477672-26f9-4a7a-b338-bb16fef8affb)
