### ISSUE TITLE
SAR is the only value given for selling price in sales and purchase information under item creation module 

### ISSUE THREAD

**Issue by AnjaliVellookkaran** [techgebra/polosys-books#116]
- [x] ![Screenshot from 2023-06-27 17-00-27](https://github.com/techgebra/polosys-books/assets/131741149/85c8a960-a55d-4210-a7b4-ed42fabaac65)

**Comment by MohdSahal** [comment]
organization's currency shown(base currency) there. no need to change currency from item creation.
@AnjaliVellookkaran check and close

**Comment by AnjaliVellookkaran** [comment]
fixed
