### ISSUE TITLE
no mandatory marking for fields in challan type

### ISSUE THREAD

**Issue by AnjaliVellookkaran** [techgebra/polosys-books#121]
![Screenshot from 2023-06-28 12-21-57](https://github.com/techgebra/polosys-books/assets/131741149/d0787534-a296-4706-a064-d563c2fe623c)

**Comment by avandhikaashokan** [comment]
bug not fixed.description field sowing required but not marked with * symbol @zahidmuhammed 
![* symbol](https://github.com/techgebra/polosys-books/assets/138277245/5e70fd94-88e9-409a-aa47-34e1f21b0937)

**Comment by avandhikaashokan** [comment]
issue fixed
