### ISSUE TITLE
ui issue in account type field of adjust stock under items module

### ISSUE THREAD

**Issue by AnjaliVellookkaran** [techgebra/polosys-books#124]
- [x] ![Screenshot from 2023-07-01 15-29-16](https://github.com/techgebra/polosys-books/assets/131741149/8ac31165-eb90-43c2-90b2-ce0db49e923c)

**Comment by AnjaliVellookkaran** [comment]
![Screenshot from 2023-07-01 15-31-58](https://github.com/techgebra/polosys-books/assets/131741149/e0dbd612-29ee-4c1b-aad7-c8791834ced8)

**Comment by MohdSahal** [comment]
@AnjaliVellookkaran please check and close

**Comment by AnjaliVellookkaran** [comment]
issue fixed
