### ISSUE TITLE
Item enhancements

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#126]
- [x] Description, type, account name(sales), purchase account name, purchase description in customize display columns.
- [x] Low stock, sales, purchase are missing in filters.
- [x] Add stock in hand, HSN in sorting; 
- [x] ascending and descending order at the time of sorting.(common)
- [x] Need filters in in slide screen of detailed view.
- [x] Refresh button in detailed page slide screen.

**Comment by avandhikaashokan** [comment]
feature done
