### ISSUE TITLE
Inventory adjustments enhancements

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#131]
- [x] Add item in bulk and another line option
- [x] Attach files
- [ ] _Reporting tags_
- [ ] _Add cost price for quantity in adjustments (entry based on entered price in such column instead of last purchase price). it only apply to stock-in in quantity adjustment._
- [x] Item name column in advanced search also need option to search with item code.
- [x] No need to show non-inventory items in listing.(services, goods without enable inventory tracking).
- [x] Period wise listing in listing page not working

**Comment by MohdSahal** [comment]
@saranya13-tech 5,6 task

**Comment by saranya13-tech** [comment]
5 is just add filter of should track inventory in listing

**Comment by zahidmuhammed** [comment]
Already Using `filter_by=active` for items api, adding another filter `filter_by=should_track_inventory`   won't work

Edit: 5 fixed by adding new params to items api `should_track_inventory:boolean`

**Comment by AnjaliVellookkaran** [comment]
ISSUE FIXED !
