### ISSUE TITLE
Customer bugs

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#145]
- [x] Address edit option from detailed view
- [x] Option to add additional address from detailed view. (delete and edit options for such address)
- [x] Show history in descending order.
- [x] Show comments in history.
- [x] Show time in comments.
- [x] Link to each transaction from customer transaction screen.
- [x] Add new button function not working as expected. need to auto select customer name by clicking add new button.
- [x] UI issues in transactions section of customer detailed view.
![image](https://github.com/techgebra/polosys-books/assets/132666132/f9d05020-7c13-42eb-971c-defddf1cfd74)
- [x] Remove customized columns option from transaction screen.
- [x] Filters not working in listing (refer overdue and unpaid)
![image](https://github.com/techgebra/polosys-books/assets/132666132/3b87d17a-f6ea-4f2d-8f0c-06907c86144f)
- [x] Bugs in statement of customer detailed view.
- [x] Other details in customers detailed view gst treatment change to vat treatment.
- [x] Remove pan, tax treatment in vendor/customer creation screen.

**Comment by avandhikaashokan** [comment]
bug fixes
