### ISSUE TITLE
deleting bug

### ISSUE THREAD

**Issue by avandhikaashokan** [techgebra/polosys-books#168]
same issue occur Both in **customer listing page** and **vendor listing page**
1)In customer listing page if customer has opening balance ,**user can't delete that customer**.
But here when we delete the customer who has opening balance,first it showing **requested URL not found**
But when we refresh, the customer has deleted already.

![delete](https://github.com/techgebra/polosys-books/assets/138277245/394c1f6a-3b25-40e1-88a2-72fd35421b9e)
![opening balance](https://github.com/techgebra/polosys-books/assets/138277245/dabd009f-d2da-42aa-b7fe-ce0b8a8d5c89)

![delete 2](https://github.com/techgebra/polosys-books/assets/138277245/a6b563f1-3e77-4678-a09e-141e8ca16e7b)
2)in vendor listing page if vendor has opening balance user can't delete that vendor

**Comment by saranya13-tech** [comment]
ERROR SOLVED
