### ISSUE TITLE
set as primary issue

### ISSUE THREAD

**Issue by avandhikaashokan** [techgebra/polosys-books#169]
Both customer detail page and vendor detail page
 if we set contact person as primary it  is not automatically change  in both customer description page and updation page 
same issue occure in vendor detail page

1: during  customer creation ,contact person
![prime 1](https://github.com/techgebra/polosys-books/assets/138277245/69261f4a-aea6-4a27-b0b3-322fe42501d9)

2:then in customer descption page like this
![prime 2](https://github.com/techgebra/polosys-books/assets/138277245/575b2487-e2e4-4ad5-8244-08e216c68e3b)

3:after set contact person as primary, the customer description page like this
![prime 3](https://github.com/techgebra/polosys-books/assets/138277245/f7723d66-9870-4010-95b4-51851c99b463)

4:then we go to the customer updation page it like
![prime 4](https://github.com/techgebra/polosys-books/assets/138277245/35179524-68a2-442a-bbd8-aca630f0db27)

**Comment by saranya13-tech** [comment]
solved
