### ISSUE TITLE
income graph bug

### ISSUE THREAD

**Issue by avandhikaashokan** [techgebra/polosys-books#172]
Both in customer module and vendor module
in income when selecting  **this fiscal year** it is not showing the graph of current year 1 April  to next year 31 March  and not mentioned the year(order is not correct)
same issue occur the graph of **previous fiscal year**
instead it showing like this
![fiscal graph](https://github.com/techgebra/polosys-books/assets/138277245/5f33df97-0fbb-4395-8ecc-503fd658eb84)

![previous](https://github.com/techgebra/polosys-books/assets/138277245/45fe4578-beaa-4aba-901c-776219a6ff91)

**Comment by saranya13-tech** [comment]
error solved

**Comment by avandhikaashokan** [comment]
year not mentioned
@saranya13-tech
