### ISSUE TITLE
income graph bug

### ISSUE THREAD

**Issue by avandhikaashokan** [techgebra/polosys-books#173]
Both in customer module and vendor module
when selecting last 12 months  grapgh ,### year not mentioned **same issue in last 6 month graph**
![12 month](https://github.com/techgebra/polosys-books/assets/138277245/fc1f10fd-2967-49b0-9a95-c95658ee7181)

**Comment by saranya13-tech** [comment]
error solved

**Comment by avandhikaashokan** [comment]
year not mentioned in graph
@saranya13-tech
