### ISSUE TITLE
sales order bugs

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#179]
- [x] Set tax preferences in dropdown at the time of edit. also show TRN number for registered customers. 

![image](https://github.com/techgebra/polosys-books/assets/132666132/dab2b4e3-090f-49bd-a6f1-9f00a62d13cd)
- [x] Tax treatment update tab not closed after such update.
- [x] No validation messages for TRN>15 digits.
- [x] Expected delivery date keep as blank. disable dates before sales order date.
- [x] Show payment terms in default based on customer creation window. 
- [x] Decimal places issue in "rate" column. (common)
- [x] At the time of edit place supply column act as editable field for all types of tax treatments.
- [x] Edit option not needed for address section without any address.
- [x] Total tax section under tax tab not include decimal places; show at least two decimal places.
- [x] Decimal places in quantity column(common). it will be show based on unit creation.
- [x] Due date not auto calculated at the time of conversion
- [x] Show 'remarks' below addresses in all sales related vouchers
- [ ]

**Comment by avandhikaashokan** [comment]
bug fixed
