### ISSUE TITLE
Item

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#182]
- [x] At the time of low stock filter, filter bar shows available quantity. (all functions are  working , bug only on text)
- [x] Stock on hand column will be blank for services and stock without enable tracking.
- [x] Purchase filter not working.
- [x] Some times purchase and sales amount not populated at the time of clone.
- [x] Unit disable at the time of edit for used items. (Bug; item used in invoices but units are still editable)
- [ ]

**Comment by avandhikaashokan** [comment]
bug fixed
