### ISSUE TITLE
Sales Return Bugs

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#196]
- [x] Add email and add new contact person functions.
- [x] Apply invoices (all invoices are listed in detailed screen; only need to list applied invoice only).
- [x] Comments and history
       1. Created with total amount.
       2. Every stage of statuses.
       3. Refund creation.
       4. Applied invoices.
       5. Update (with total amount)
       6. Refund deleted.
       7. Apply credit deleted.
       8. Edit of refund(with amount)
       9. Edit of apply invoices.
- [x] Apply invoices and refund option not needed after applied all amount of credits.
- [x] After applied credit or refund option against sales return; No need void and delete function.
- [x] Status change after applied all amount of credit. (it will be closed status).
- [x] Set cash as default value in payment mode column in refund screen. (common)
- [x] Show 'submitted by' and 'approved by' in detailed view.

### Missing Features
- [x] Import and export option
- [x] View journal in detailed view.

**Comment by avandhikaashokan** [comment]
bug fixed
