### ISSUE TITLE
Retainer Invoices

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#198]
- [x] Need to show 'submitted by' after pending for approval status and 'approved by'and 'approval details after approval stage.
- [x] Upload file in record payment not working.
- [x] Thank you note in record payment section.
- [x] Pass default date in record payment section.(today date).
- [x] Date missing at the time of edit. (record payment).
- [x] Email and contact person creation section missing at the time of edit of retainer invoices.
- [x] Buttons in edit screen (feature)
       1. In draft (Save, save and submit, 'save and send' and 'save and approval')
       2. In pending for approval (Save, 'save and approval' and 'save and send')
       3. All stages after Approval (Save, save and send)
- [x] Show currency with total amount in creation screen.
- [x] Refund of one retainer shown in all new created retainers.

### NEW UPDATES

- [ ]

**Comment by avandhikaashokan** [comment]
bug fixed
