### ISSUE TITLE
import bug in price list

### ISSUE THREAD

**Issue by avandhikaashokan** [techgebra/polosys-books#215]
- [x] while import **all items price list** it redirect to blank page
![Screenshot from 2023-08-21 18-16-32](https://github.com/techgebra/polosys-books/assets/138277245/3495f584-0908-41f5-961b-645e4457c8c7)
- [x] in csv file Rename **is for** - **Transaction type**
2) bug in **import unit items price list**
- [x] while importing unit item pricelist it showing imported successfully,but not listed in pricelist page
![Screenshot from 2023-08-21 17-29-31](https://github.com/techgebra/polosys-books/assets/138277245/53a8dee1-b2f1-4045-90eb-640dcc2e033d)
- [x]  in csv file change the name ** Is For**  to transaction type
- [x] price list type column not provided
- [x] currency colunm not provided in csv file
- [x] if we not provided mandatory data's in csv file ,then importing it showing internal server error. 
- [x] if we enter invalid item in csv file,then importing it showing error with tick mark
![Screenshot from 2023-08-21 18-09-54](https://github.com/techgebra/polosys-books/assets/138277245/935ca606-625e-4f38-a452-903b0487090f)

**Comment by MohdSahal** [comment]
issue closed
