### ISSUE TITLE
Item Bugs 3.0

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#216]
- [x] Item image section: only need to accept image files ( no need option to select pdf, doc etc...)
- [x] Keep opening stock ,rate and re-order level as non mandatory field.
- [x] Track inventory tick box at the time of clone (tick not shown)
![image](https://github.com/techgebra/polosys-books/assets/132666132/0ec3d70b-52b7-457d-9013-220d28ae2188)

- [x] Sort: name, stock on hand, last modified time not working.
- [x] Filter: Purchases- only need to show purchase information true items. (currently other items are listing in this filters)
- [x] Customise columns: Purchase account name keep as blank for services without enable purchase information at the time of creation.
- [x] Re-order level and opening stock more than 2 decimal issue
- [x] Keep all amount columns exclusively for float.
- [x] Sort option not working

**Comment by AnjaliVellookkaran** [comment]
these issues are not yet fixed @saranya13-tech 
- [x] tick is not shown at the time of clone 
- [x] stock on hand sort is not working
- [x] filter -all items are listed under purchase filters
![Screenshot from 2023-10-06 12-24-36](https://github.com/techgebra/polosys-books/assets/131741149/bde816ba-c422-446a-ab38-e490bdc1a909)

**Comment by MohdSahal** [comment]
Completed
