### ISSUE TITLE
Customers

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#22]
- [x] Crud
- [x] Preferences
- [x] Sort 
- [x] Import customer more columns required
- [x] Email customer option in listing
- [x] Bulk actions like email to customer,print,bulk update,mark active,mark inactive,merge and associate templates in listing screen. show attach symbol for customer's with attachment.
- [x] Show address in primary language and secondary language in customer detailed window. address creation from customer detailed window keep like address creation in customer creation. show remarks in detailed view(in overview).
- [x] Graph and filters in item detailed view based on sales and returns.
- [x] 'status Filter' and 'add new' functions in transaction tab in customer detailed view.
- [x]  List customer related sent bills in mails section in customer detailed view with details, date and time.
- [x] Need filter option for outstanding in statement section in customer detailed window. need custom date section in date filter. 'customer statement for' then use display name instead of first and last name. show organisation name and address also set to address name with customer address. send mail function not properly working like zoho books.
- [x] Attach files (maximum size limit to 5 mb, maximum files limit to 10) and also show such limits in attach files screen. attachment delete option not working. need remove option in addition to delete function. need popup for confirmation for remove and delete. store attached files in documents module. download attachment option. show count of attach files. 
- [x] Add recurring expense creation in new transaction option.
- [x] Associate templates, email to customer(not properly working), stop all reminders, link to  vendor, merge customer. Remove configure customer portal options.
- [x] Create and edit screen: tax number column only need to show if such party registered.validate TRN with portal. rename tax number to tax registration number(TRN). Give default POS based on tax treatment. organisation's currency set as currency in default. terms rename to payment terms. set due on receipt as default payment term. contact person show more fields button. 
- [x] Designation and department field keep like additional info.
- [x] Change customer data by changing of primary contact person. actions like edit, delete, send mail and make primary for contact person.

**Comment by MohdSahal** [comment]
view details option not needed for customer creation and update in 'activity log'. only need this function for transactions.

**Comment by MohdSahal** [comment]
mark inactive function not working. customer still like active.

**Comment by MohamedRoshanPU** [comment]
### Attach Files
- Download Issue
- document module

**Comment by MohamedRoshanPU** [comment]
### Bulk Actions
- Print
- Associate Templates

**Comment by MohamedRoshanPU** [comment]
### More Actions
- Associate Templates
- Send Mail

**Comment by MohamedRoshanPU** [comment]
### Statement
-Send Mail

**Comment by MohdSahal** [comment]
completed
