### ISSUE TITLE
Bug in Retainer invoice

### ISSUE THREAD

**Issue by AnjaliVellookkaran** [techgebra/polosys-books#258]
- [x] description and amount not taken at the time of creation
- [x] need popup for reason and it must be shown in comments and history section
- [x] block entering negative values in columns
- [x] need to erase data at the time of 'convert to draft'
- [x] set two conditions for apply invoice
- [x] no need to show invoices with amount applied zero
- [x] status not changed after apply full amount against invoices
- [x] delete not working and need proper message for requirements unsatisfied retainers
- [x] need popup for reason and it must be shown in comments and history section
- [x] need to show submitted by and approved by details as creators name
- [x] invoices delete,status changed to drawn
- [x] need popup for submit for approval
- [x] need popup for approval
- [x] edit button in rejected stage- "save" and "save and submit"
- [x] status change after delete of refund section is showing status as still drawn
- [x] available credits not updated (unused amount) in apply invoice delete
- [x] edit from pending for approval stage and add save and approval button
- [x] while editing from sent stage,Only need to show save, save and send button
- [x] need popup and option to enter reason in void stage

**Comment by AnjaliVellookkaran** [comment]
@MohamedRoshanPU please recheck this issue

**Comment by MohamedRoshanPU** [comment]
Frontend Fixed

**Comment by AnjaliVellookkaran** [comment]
issue fixed!
