### ISSUE TITLE
Bug in payment received

### ISSUE THREAD

**Issue by AnjaliVellookkaran** [techgebra/polosys-books#263]
- [x]  only need to show in invoice# section in listing view
- [x] No need filters/ give only one option like all payments
- [x] in Payment record against invoices,amount section type keep as float
- [x]  under Payment record against invoices, negative number block
- [x]  under payment received /made column,negative number block
- [x] under refund edit section,Wrong balance amount after edit of partial refund
- [x] under refund delete section,Wrong balance amount after delete of partial refund
- [x] under update section,can't update without any change- wrong popup(created with full amount)
- [x] under update section,received full amount, apply amount missing
- [x] under opening balance section,no need to show opening balance in listing; if opening balance===0
- [x] under update section(enhancement),Vendor/customer name can't change at the time of update
- [ ] under creation screen,pass message like "There are no unpaid invoices associated with this customer."
- [x] under accounts entry section,not updated by edit
- [x] under history section,show edit and refund details in history section
- [x] view journal in detailed screen
- [x] show due date in edit screen
- [x] under bank charges,credit ledger change to "selected ledger" from "accounts receivable"
- [x] under filter option,add retainer payments and invoice payments
- [x] under create and update of bank charges,The Bank Charges can't be more than the amount received.
- [x] under create and update of bank charges,Bank charges are applied. Please select a bank account.

**Comment by avandhikaashokan** [comment]
- [ ] under history section,show edit details . but here the content is invalid
