### ISSUE TITLE
Payments Received

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#28]
- [x] Crud
**IN CREATION SCREEN**
- [x] No relevance addresses in creation screen.
- [x] Bank charges function(back end)
- [x] Set payment mode in default **cash** and deposit to account in default **main safe**.(add at least bank and cash in default)
- [x] Need manage payment mode option to choose default payment mode,add or remove.
- [x] No need bank account column.
- [x] Button rename to save(edit also)
- [x] Attach files
- [x] Notes for internal use
- [x] Email to "thanks notes"
**IN DETAILED VIEW**
- [x] Send mail options
- [x] View journal
- [x] Remove clone and void options
- [x] Refund option for balance amount not applied for invoices.
- [x] Show payment history
- [x] Delete function not working
- [x] Show 'deposit to account' in detailed view
- [x] Template change option.
IN LISTING
- [x] More columns in listing
- [x] Manage custom fields
- [x] Bulk actions like delete,mail, print,pdf,bulk update.

- [x] Preferences

**Comment by MohdSahal** [comment]
PAY IN FULL, APPLY AMOUNT MISSING AT THE TIME OF EDIT

**Comment by MohdSahal** [comment]
PAID THROUGH ACCOUNT BUG(NEED TO RE SELECT EVERY TIME)
Apply amount tick auto remove when client edit amount manually.
In edits pay in full function not working correctly.(it only reflect balance amount after save same voucher)

**Comment by saranya13-tech** [comment]
need payment mode manage option

**Comment by MohdSahal** [comment]
Completed
