### ISSUE TITLE
Vendor

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#31]
- [x] Crud
- [x] Sort 
- [x] Email customer option in listing
- [x] Bulk actions like email to vendor,print,bulk update,mark active,mark inactive,merge and associate templates,delete in listing screen.
- [x] Show address in primary language and secondary language in customer detailed window. address creation from vendor detailed window keep like address creation in vendor creation.
- [x] Graph and filters in item detailed view based on sales and returns.
- [x] 'status Filter' and 'add new' functions in transaction tab in customer detailed view.
- [x]  List vendor related sent bills in mails section in customer detailed view with details, date and time.
- [x] Need filter option for outstanding in statement section in customer detailed window. need custom date section in date filter. 'customer statement for' then use display name instead of first and last name. show organisation name and address also set to address name with customer address. send mail function not properly working like zoho books.
- [x] Attach files (maximum size limit to 5 mb, maximum files limit to 10) and also show such limits in attach files screen. attachment delete option not working. need remove option in addition to delete function. need popup for confirmation for remove and delete. store attached files in documents module. download attachment option. show count of attach files. 
- [x] Add recurring bill, recurring expenses creation in new transaction option.
- [x] Associate templates, email to vendor(not properly working), link to  customer, merge vendors,clone. Remove add bank account.
- [x] Create and edit screen: tax number column only need to show if such party registered.validate TRN with portal. rename tax number to tax registration number(TRN). Give default SOS based on tax treatment. organisation's currency set as currency in default. terms rename to payment terms. set due on receipt as default payment term. contact person show more fields button. 
- [x] Designation and department field keep like additional info.
- [x] Change vendor data by changing of primary contact person. actions like edit, delete, send mail and make primary for contact person.

**Comment by MohamedRoshanPU** [comment]
### Statement
- Send Mail

**Comment by MohamedRoshanPU** [comment]
### More Actions
- Associate Templates
- Send Mail

**Comment by MohamedRoshanPU** [comment]
### Bulk Action
- Print
- Associate Templates

**Comment by MohamedRoshanPU** [comment]
### Attachment
- Document Module
- Download

**Comment by MohdSahal** [comment]
Completed
