### ISSUE TITLE
not able to view vendor or search&select vendor from dropdown under any of the creation screens under purchase module

### ISSUE THREAD

**Issue by AnjaliVellookkaran** [techgebra/polosys-books#322]
![Screenshot from 2023-11-03 11-31-28](https://github.com/techgebra/polosys-books/assets/131741149/55e1c220-a807-4787-8419-ad8f408afeec)
![Screenshot from 2023-11-03 11-31-21](https://github.com/techgebra/polosys-books/assets/131741149/84ed27e2-04e1-4f2d-9b7c-5a73bd17c850)

**Comment by MohamedRoshanPU** [comment]
Couldn't recreate Bug

**Comment by avandhikaashokan** [comment]
issue solved
