### ISSUE TITLE
Bugs in organization profile

### ISSUE THREAD

**Issue by AnjaliVellookkaran** [techgebra/polosys-books#340]
- [x] spelling mistake and invalid text
![Screenshot from 2023-11-30 12-41-34](https://github.com/techgebra/polosys-books/assets/131741149/7f9bd817-a459-48be-b12d-620c3d4c3295)

- [x] under organization address(In Primary Language):-State/province (mandatory field)
- [x] phone number -non mandatory field
- [x] Navigation to ‘organization’s address format’
![Screenshot from 2023-11-30 14-16-25](https://github.com/techgebra/polosys-books/assets/131741149/3ad37857-f01a-44cd-b2c0-1ea7bdcf0c75)
- [x] keep company id as non mandatory field
- [x] cancel button needed
- [x] give an outline for payment stub address field
- 
![Screenshot from 2023-11-30 14-20-49](https://github.com/techgebra/polosys-books/assets/131741149/f68c2128-d23b-4adc-b049-fabb7d3319d1)

**Comment by midhunkrishnanr07** [comment]
this issue is fixed

**Comment by AnjaliVellookkaran** [comment]
@midhunkrishnanr07 @MohamedRoshanPU please rename the invalid text given above "delete organization logo"

**Comment by midhunkrishnanr07** [comment]
> @midhunkrishnanr07 @MohamedRoshanPU please rename the invalid text given above "delete organization logo"

This issue is now fixed

**Comment by AnjaliVellookkaran** [comment]
issue fixed !
