### ISSUE TITLE
Bugs under recurring journal

### ISSUE THREAD

**Issue by AnjaliVellookkaran** [techgebra/polosys-books#348]
- [x] 500 internal server error-Manually creation of manual journal from recurring journal detail page by clicking save and publish button
- 
![Screenshot from 2023-12-01 14-08-23](https://github.com/techgebra/polosys-books/assets/131741149/e5014605-0d6f-442f-8347-e39a5443274d)

**Comment by MohamedRoshanPU** [comment]
Couldnt Recreate Bug

**Comment by avandhikaashokan** [comment]
issue solved
