### ISSUE TITLE
Payment Made

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#36]
- [x] Crud
**IN CREATION SCREEN**
- [x] No relevance addresses in creation screen.
- [x] Set payment mode in default **cash** and deposit to account in default **main safe**.(add at least bank and cash in default)
- [x] Need manage payment mode option to choose default payment mode,add or remove.
- [x] Button rename to save(edit also)
- [x] Attach files
- [x] Notes for internal use
**IN DETAILED VIEW**
- [x] Send mail options
- [x] View journal
- [x] Refund option for balance amount not applied for invoices.
- [x] Show payment history
- [x] Delete function not working
- [x] Show 'deposit to account' in detailed view
- [x] Template change option.
IN LISTING
- [x] More columns in listing
- [x] Bulk actions like delete,mail, print,pdf,bulk update.

- [x] Preferences

**Comment by MohamedRoshanPU** [comment]
- template option in payment made not completed as templates module is not finished
- manage option for payment mode not done

**Comment by MohdSahal** [comment]
Completed
