### ISSUE TITLE
Vendor credits

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#38]
- [x] Crud
**IN CREATION SCREEN**
- [x] Remove source and destination of supply
- [x] Remove bill type column
- [x] Need columns to show debit note number(vendor credit no)
- [x] Use save and submit instead of save and send.
**IN DETAILED VIEW**
- [x] In draft stage: 1. Apply to bills option 2. Submit for approval button
- [x] In Submit for approval: 1. add this status and ensure convert to draft, apply to bills function. 2. buttons in edit: save, save and approve.
- [x] In approved stage: 1. buttons in edits: save
- [x] In rejected stage: 1. resubmit 2. clone 3. view journal 4. delete
- [x] In void stage(currently not working): 1. clone, view journal, delete, covert to draft 2. no need edit option.
- [x] show submit by and approved by user.(also give option to see approver's details.)
- [x] comments and history
- [x] In clone function against bills must be blank.  
- [x] New button and filters in detailed view(listing).
- [x] Void with reason.
- [x] Delete
- [x] View journal
- [x] No need mail option
- [x] Show applied bills in detailed view.
**IN LISTING VIEW**
- [x] Wrong sort options
- [x] Wrong filter options
- [x] Custom view
- [x] Path to preferences

- [x] Preferences

**Comment by avandhikaashokan** [comment]
feature done
