### ISSUE TITLE
Manual journal

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#39]
- [x] Crud
- [x] 'Choose template' option in creation screen
- [x] No need exchange rate column for base currency selection
- [x] Set two lines in default for journals
- [x] Additional information in table headings(to access reporting tags) to apply all line of journal. need same button in each line of journal to access reporting tag in specified line of journal.
- [x] Attach files in creation screen.
- [x] Make recurring function in creation screen.
- [x] In draft stage: 1. No need option for mail 2. Show templates in detailed view. 3. print&pdf option 4.clone 5.create template(journal template,not actual template) 6.delete. 7. 'mark as published' rename to 'publish'.
- [x] In published stage: 1. all options in draft stage(other than publish button) 2. Create reverse entry. 3. edit: only need publish button(also ensure button working properly-currently publish button in edit changed status to draft.).
- [x] Import journals in listing
- [x] Manage templates in listing
- [x] Manage custom fields in listing
- [x] 'NEW' button includes functions 1. new journal 3.create from templates 3.new templates 4.new recurring journal
- [x] Remove sent from status filters in listing
- [x] Remove difference amount from item listing.
- [x] Accountant Preferences
- [x] Ledger search with accounts code and group wise ledger search.

**Comment by avandhikaashokan** [comment]
features done
