### ISSUE TITLE
Payable Summary

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#424]
- [x] Date field blank
![image](https://github.com/techgebra/polosys-books/assets/132666132/948d6a44-c8e1-42d1-bd2d-00fe765880a9)

- [x] Wrong values in entities Dropdown (use Bill, vendor credit and expenses)
![image](https://github.com/techgebra/polosys-books/assets/132666132/ef037ea8-ad28-42c8-a94c-ed7f08564d99)

- [x] Group by bills's due date and expected delivery date fields are missing
- [x] Payment Summary data Customization not working (even after clear all customization, report not generated)
- [ ]

**Comment by midhunkrishnanr07** [comment]
check this bug, normal report is working. On customization empty array is returning @saranya13-tech
