### ISSUE TITLE
Retainer Invoice payment record section

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#431]
- [x] Set cash safe in default
- [x] Only need to show 'cash', 'bank' and 'other current liabilities' in 'deposit to' Dropdown.
- [x] Attached files are missing at the time of edit.

**Comment by AnjaliVellookkaran** [comment]
- [x] ![Screenshot from 2023-12-18 11-46-16](https://github.com/techgebra/polosys-books/assets/131741149/1e7b80dc-272c-4398-ad59-73b0b928f8f4)
![Screenshot from 2023-12-18 11-46-26](https://github.com/techgebra/polosys-books/assets/131741149/60344927-09e2-4864-97d7-c7607afc509f)

**Comment by AnjaliVellookkaran** [comment]
issue fixed !
