### ISSUE TITLE
Sales by customer

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#439]
- [x] Set  'invoice' as default value for entities.
- [x] 'credit notes' rename to 'sales return' in 'entities' dropdown.
- [x] No compare with function
- [x] No customization function in drilled down view of 'sales by customer' report
- [x] Set default value '1' for number of periods/years section.
- [x] Customization not working.

**Comment by midhunkrishnanr07** [comment]
@saranya13-tech customization data not coming
