### ISSUE TITLE
Item Clone

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#443]
- [x] Barcode displayed 'undefined' for item saved without barcode.
![image](https://github.com/techgebra/polosys-books/assets/132666132/9a76cb3a-d560-47e9-b9a0-c7a9bb590df8)

- [x] At the time of edit
![image](https://github.com/techgebra/polosys-books/assets/132666132/cb84f4ab-32b8-44fd-9c60-d45a1461c973)

**Comment by AnjaliVellookkaran** [comment]
issue fixed !
