### ISSUE TITLE
Payment received

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#454]
- [ ] Invoice listing Issue
Steps
1. Create invoice as credit.
2. Pay full amount through Payment received.
3. Delete that payment received.
4. Then record payment through 'payment record' section. (no data)
after this transaction invoice still paid status
![image](https://github.com/techgebra/polosys-books/assets/132666132/be5796cd-2481-4b11-8e36-7487c291198a)

**Comment by AnjaliVellookkaran** [comment]
issue fixed!
