### ISSUE TITLE
Validation for Invoice/debit notes deletion

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#456]
- [ ] If credit applied against invoices
"This invoice has credits applied to it. Hence, it cannot be deleted."

- [ ] If Used to create sales return (selected from creation screen)
"Cannot delete as one or more credit notes are created from this invoice. Credit Notes - [CN-00043, CN-00045]"

**Comment by AnjaliVellookkaran** [comment]
ISSUE FIXED!
