### ISSUE TITLE
remove place of supply field for non gcc tax treatments under purchase module

### ISSUE THREAD

**Issue by AnjaliVellookkaran** [techgebra/polosys-books#457]
- [x] under create new vendor credits
- [x] under create new purchase orders
- [x] under create new bills
- [x] under create new recurring bills
![Screenshot from 2023-12-12 14-31-28](https://github.com/techgebra/polosys-books/assets/131741149/ab1043ff-50df-442c-bd54-9366afe97f62)

**Comment by MohamedRoshanPU** [comment]
Its not a bug. its a feature.

**Comment by AnjaliVellookkaran** [comment]
ok..issue no longer exist! Hence closing
