### ISSUE TITLE
Debit notes Bug

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#459]
- [x] Approved stage
![image](https://github.com/techgebra/polosys-books/assets/132666132/87d4019a-077f-401c-9640-c2c5f58b2bee)

- [x] Journal not displayed
![image](https://github.com/techgebra/polosys-books/assets/132666132/4e1244fb-1921-4d09-9cac-f2276ebd6a3e)

- [x] Record Payment section: debit note number missing (payment for section)
![image](https://github.com/techgebra/polosys-books/assets/132666132/a8b4d772-9a7e-418a-b310-67b33d54bc7a)

- [x] Record payment section: set 'cash' in payment mode section
- [x] Record payment section: set 'cash safe' deposit to account' section
- [x] Record payment section: deposit to account dropdown only need to show 'bank', 'cash' and 'Other current liabilities'

**Comment by AnjaliVellookkaran** [comment]
issue fixed!
