### ISSUE TITLE
Debit note creation 

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#461]
- [x] Place of supply function not properly working (Non vat registered)
- [x] Set sales account in default (in select account field)
![image](https://github.com/techgebra/polosys-books/assets/132666132/98d7d1a7-76cd-4870-9625-8121fda53af0)

- [x] Set 'default tax' rate in in creation screen
![image](https://github.com/techgebra/polosys-books/assets/132666132/0942489b-6d06-4bdf-8dbb-5ccdbfc66d23)

**Comment by AnjaliVellookkaran** [comment]
issue fixed !
