### ISSUE TITLE
Debit note: Draft and submit for approval stage

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#463]
- [x] Associate invoice and details are missing
![image](https://github.com/techgebra/polosys-books/assets/132666132/8ddac013-e316-48ec-a158-583fddb5c3d0)
![image](https://github.com/techgebra/polosys-books/assets/132666132/ed255108-ec1c-471e-901a-0799cfa579e5)

**Comment by AnjaliVellookkaran** [comment]
issue fixed !
