### ISSUE TITLE
Preferences in relation to debit notes

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#467]
**Through General Preferences**

- [x] Pdf attachment 
![image](https://github.com/techgebra/polosys-books/assets/132666132/19e6f72d-3c50-4bc1-807f-2e2b68574f63)

- [x] Discount
![image](https://github.com/techgebra/polosys-books/assets/132666132/dba66f2e-d989-4ab7-8abb-6c72b185a39c)

- [x] Tax inclusive and exclusive functions
![image](https://github.com/techgebra/polosys-books/assets/132666132/8b71c429-71a6-4bb5-81b1-bb6430a9d5e3)

- [x] Sales person
![image](https://github.com/techgebra/polosys-books/assets/132666132/85842a4e-f44c-4ae3-b436-efcc7b548216)

**Through Invoice Preferences**

- [x] Allow editing of sent invoice
![image](https://github.com/techgebra/polosys-books/assets/132666132/2d694687-16e8-44f6-baf6-5e6975c1d70d)

- [x] QR code 
![image](https://github.com/techgebra/polosys-books/assets/132666132/913694af-bfd5-43b3-8cee-5adec940326d)

- [x] Terms and Conditions
![image](https://github.com/techgebra/polosys-books/assets/132666132/89189bbc-aa61-4ee0-ad87-5518b8de00e0)

- [x] Customer notes
![image](https://github.com/techgebra/polosys-books/assets/132666132/9c93b8d3-c2a3-43a3-97ed-e403a433138a)

**Comment by AnjaliVellookkaran** [comment]
issue fixed !
