### ISSUE TITLE
display valid account for bank&cash under invoices

### ISSUE THREAD

**Issue by AnjaliVellookkaran** [techgebra/polosys-books#468]
- [x] show default value for cash account field as cash safe 
- [x] display dropdown values for bank account field 
-
![Screenshot from 2023-12-12 17-24-30](https://github.com/techgebra/polosys-books/assets/131741149/eea8613b-f5e2-423c-905f-52d5a3d5b685)

![Screenshot from 2023-12-12 17-29-46](https://github.com/techgebra/polosys-books/assets/131741149/8df50d1e-8ce4-483f-9436-272031d17f00)

**Comment by MohamedRoshanPU** [comment]
Frontend Bug Fixed

**Comment by AnjaliVellookkaran** [comment]
issue fixed!
