### ISSUE TITLE
'To bills' module

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#488]
### Conversion from Purchase order
- [x] RCM function not properly working (Rcm displayed for 'vat registered')
![image](https://github.com/techgebra/polosys-books/assets/132666132/10d8ba3f-611e-4eff-9702-b24c38a785da)

- [x] Default eligible in tax field
![image](https://github.com/techgebra/polosys-books/assets/132666132/b77994a3-4e2c-41c8-888a-21cd9bdbc86a)

- [x] Discount type set as transaction level, but discount column displayed in line item level
function: this feature need to work based on conversion voucher. (purchase order to bill conversion)
![image](https://github.com/techgebra/polosys-books/assets/132666132/847c66ac-e52d-4fa6-a905-f285b180c3eb)

- [x] Save in approved stage (But, status still draft)

**Comment by AnjaliVellookkaran** [comment]
ISSUE FIXED !
