### ISSUE TITLE
Item creation/edit screen

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#496]
- [x] Opening stock quantity column just clicked and not enter any quantity. then click 'save', (message:opening stock qty required)
- [x] opening stock removal through edit issue
![image](https://github.com/techgebra/polosys-books/assets/132666132/0d3ff525-4670-49b9-8d48-3995eccdcd2a)

**Comment by AnjaliVellookkaran** [comment]
issue fixed !
