### ISSUE TITLE
Payment Received (Amount due calculation)

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#502]
- [x] Wrong amount displayed in total amount column
Steps:
1. Invoice created for Rs. 1000
2. Record payment rs.300 through payment received
3. Then, invoice edited to Rs. 1500
4. Then, record payment section (total amount due wrong amount displayed)
Expected output= 1200 (1500-300)
Actual output=1500

**Comment by AnjaliVellookkaran** [comment]
issue fixed!
