### ISSUE TITLE
purchase order

### ISSUE THREAD

**Issue by avandhikaashokan** [techgebra/polosys-books#509]
- [x] edit not functioning (and customer address is not showing)
- [x] customer address  edit not functioning
-
![Screenshot from 2023-12-15 18-11-41](https://github.com/techgebra/polosys-books/assets/138277245/84d4df95-bdd7-4cda-a6ef-70e0cb15168a)
![Screenshot from 2023-12-15 18-12-14](https://github.com/techgebra/polosys-books/assets/138277245/16680bb7-c699-4e07-8872-e8af743c38df)

**Comment by AnjaliVellookkaran** [comment]
issue fixed !
