### ISSUE TITLE
Payment Received edit

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#511]
- [x] Double entry in payment received
Steps:

1. Create invoice for Rs. 1000 as credit
2. Record payment Rs.500 through payments received
3. Then click edit payment received and attach file 
4. Click save.
5. Then click payment received edit
Expected Result: amount due= 1000
Actual Result: amount due= 0

- [x] Same issue in payments made

**Comment by AnjaliVellookkaran** [comment]
issue fixed
