### ISSUE TITLE
tax treatment and place of supply are displayed under the expense creation screen 

### ISSUE THREAD

**Issue by AnjaliVellookkaran** [techgebra/polosys-books#521]
![Screenshot from 2023-12-16 09-51-51](https://github.com/techgebra/polosys-books/assets/131741149/02aedfd1-afb6-4851-98af-c3a0e956942a)

**Comment by MohamedRoshanPU** [comment]
This feature is not in zoho.

**Comment by AnjaliVellookkaran** [comment]
tax treatment and place of supply are displayed under the expense creation screen while creating new transaction from vendors
@MohamedRoshanPU

**Comment by AnjaliVellookkaran** [comment]
![Screenshot from 2023-12-19 10-53-26](https://github.com/techgebra/polosys-books/assets/131741149/4f6907ed-417c-4961-a225-297cfc482cd3)
requested url not found message is displayed each time when expense is clicked from transactions

**Comment by AnjaliVellookkaran** [comment]
issue fixed !
