### ISSUE TITLE
issues under sales order

### ISSUE THREAD

**Issue by AnjaliVellookkaran** [techgebra/polosys-books#535]
- [x] popup windows are missing
- convert from draft to submit for approval stage
- convert from submit for approval to approved stage
- [x] converting to invoice from confirmed stage -default account for amount received is given as bank(change it to credit)

**Comment by zahidmuhammed** [comment]
- Task 2 - Note : Default account for amount received is changed to credit

**Comment by AnjaliVellookkaran** [comment]
ok

**Comment by AnjaliVellookkaran** [comment]
issue fixed !
