### ISSUE TITLE
'To sales order' module

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#540]
- [x] 'Expected Delivery Date' not a mandatory field.
![image](https://github.com/techgebra/polosys-books/assets/132666132/a791d010-5842-4bfd-a551-478726c2a494)

- [x] 'Sales person' not a mandatory field.
![image](https://github.com/techgebra/polosys-books/assets/132666132/58765a20-f0ff-4c01-abf3-2cad41141efd)

- [x] 'Due date' column not required.
![image](https://github.com/techgebra/polosys-books/assets/132666132/a9d45d91-093a-40c4-a7ae-d40c97743c6a)

- [x] Inter change 'sales order date' and 'Expected delivery date'.
- [ ]

**Comment by AnjaliVellookkaran** [comment]
issue fixed !
