### ISSUE TITLE
'To purchase order' module

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#544]
- [x] Discount switching field for transaction level and line item level in the above of item table.
- [x] Transaction level discount feature. (hide line item level discount column)
- [x] After and before tax discount in transaction level.
- [x] 'Submit' button rename to 'save as draft'.
![image](https://github.com/techgebra/polosys-books/assets/132666132/aa24fb6d-1819-4423-8b53-c81dae68a256)
- [x] Address section not required
![image](https://github.com/techgebra/polosys-books/assets/132666132/9b9e2b33-75cb-4475-8df0-abba9d28c2c9)

**Comment by MohdSahal** [comment]
@AnjaliVellookkaran

**Comment by AnjaliVellookkaran** [comment]
issue fixed !
