### ISSUE TITLE
In all Purchase modules

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#545]
- [x] Account column in item table for all purchase modules (Bills, to bills, purchase order, to purchase order, recurring bills)

1. Show 'Default inventory account' for inventory tracking items.
2. Show 'Default purchase account' for Non inventory tracking items. ('cost of goods sold' for 'non inventory items' without default purchase account.

**Comment by AnjaliVellookkaran** [comment]
issue fixed !
