### ISSUE TITLE
Actions from sales order detailed screen

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#549]
- [x] Validation message for record payments. (for statuses before sent.)
- [x] Delete function validation for 'Partially paid' and 'paid' status invoices.

![image](https://github.com/techgebra/polosys-books/assets/132666132/5b8b6e4a-17a7-4bf2-979f-2ac042ea0739)

**Comment by AnjaliVellookkaran** [comment]
issue fixed !
