### ISSUE TITLE
Price list inactive validations in conversions

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#551]
- [x] Sales order to invoice

- [x]  Estimate to sales order

- [x]  Estimate to invoices

- [x]  Delivery challans to invoices

- [x]  Purchase order to bills

 

- [x] Bill to recurring bills (detailed view)

- [x]  Invoice to Recurring invoice (detailed view)
- [x] Instead invoice

**Comment by AnjaliVellookkaran** [comment]
issue fixed !
