### ISSUE TITLE
Expenses & recurring Expenses creation and edit screen

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#596]
- [x] Tax field mandatory for 'vat registered' transactions.
- [x] 'GCC vat registered', GCC non vat registered' and 'non GCC'. These 3 vat treatments are reverse charge applicable; need validation for RCM.

- [x] For RCM transactions user need to choose Tax for this transactions.

**Comment by AnjaliVellookkaran** [comment]
issue fixed !
