### ISSUE TITLE
Sales order to purchase order conversion

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#618]
- [x] Popup for Purchase information items at the time of conversion.
- [x] No need to convert purchase information unticked items.

**Comment by zahidmuhammed** [comment]
[1] 
![image](https://github.com/techgebra/polosys-books/assets/67199747/789cbfc2-1aa1-4aab-baa6-eeceee018470)

**Comment by AnjaliVellookkaran** [comment]
issue fixed !
