### ISSUE TITLE
spelling of packing slips under preferences in settings module is not correct

### ISSUE THREAD

**Issue by AnjaliVellookkaran** [techgebra/polosys-books#64]
packings Lips

**Comment by AnjaliVellookkaran** [comment]
please recheck the issue @MohamedRoshanPU

**Comment by AnjaliVellookkaran** [comment]
![Screenshot from 2023-08-02 17-25-48](https://github.com/techgebra/polosys-books/assets/131741149/56a91049-a6f4-4a43-8ca6-f3f5fb8ac22a)

**Comment by avandhikaashokan** [comment]
issue closed
