### ISSUE TITLE
save and submitt button not functioning  

### ISSUE THREAD

**Issue by avandhikaashokan** [techgebra/polosys-books#640]
- [x] while doing conversion from delivery challan to invoice
- in zoho,a popup window is displayed to automatically approve the created invoice
- 
![Screenshot from 2024-01-01 10-49-24](https://github.com/techgebra/polosys-books/assets/131741149/973df0f2-ab0a-46d7-9fac-7dc012c776b1)
- [x] clicking on save and submit button from invoice page must be creating pending approval status as its submitting for approval
- 
![Screenshot from 2024-01-01 11-21-45](https://github.com/techgebra/polosys-books/assets/131741149/a574af83-6844-4f90-b021-cc6554806618)

- [x] while doing conversion from sales order  to invoice
- [x] popup windows are missing while clicking on convert to invoice option from sales order draft status
- 
![Screenshot from 2024-01-01 11-32-15](https://github.com/techgebra/polosys-books/assets/131741149/a8151070-ae2a-42fd-a885-f5bc23c7a702)
![Screenshot from 2024-01-01 11-32-26](https://github.com/techgebra/polosys-books/assets/131741149/3eef3ec2-c424-42df-a9a6-797e2843f82b)

**Comment by AnjaliVellookkaran** [comment]
issue fixed !
