### ISSUE TITLE
no asterisk symbol for all required fields

### ISSUE THREAD

**Issue by AnjaliVellookkaran** [techgebra/polosys-books#66]
by filling marked mandatory fields,not able to perform any operations.but after filling all the given fields in normal,we are able to perform the same tasks

**Comment by avandhikaashokan** [comment]
under setting module 
- [x] in brands creation page name & code field is required but not marked with * symbol
- [x] in category  creation page  name & code field is required but not marked with * symbol
- [x]  in payment terms creation page  name & no.of days  field is required but not marked with * symbol
- [x] in  payment mode name & Is Payment Mode Cash  is required but not marked with * symbol
- [x] in delivery challan types creation page  name  field is required but not marked with * symbol
- [x] in credit reasons creation page  name & description field is required but not marked with * symbol
- [x] in entity type creation page Entity Type Name field is required but not marked with * symbol
- [x] in repeat master creation page  Name & days  field is required but not marked with * symbol
- [x] in unit class creation page  Name & description field is required but not marked with * symbol
- [x] n units creation page  Name,description & unit class field is required but not marked with * symbol
and in unit class creation name & description field is required but not marked with * symbol
![mandatory](https://github.com/techgebra/polosys-books/assets/138277245/8f01abcf-3157-489b-b839-c54d36093731)
- [x] in address type creation page name & is for field is mandatory but not marked with * symbol
@saranya13-tech

**Comment by AnjaliVellookkaran** [comment]
issue fixed !
