### ISSUE TITLE
issue under record payment : under retainer invoice

### ISSUE THREAD

**Issue by avandhikaashokan** [techgebra/polosys-books#668]
- [ ] refresh issue

![Screenshot from 2024-01-11 12-48-28](https://github.com/techgebra/polosys-books/assets/138277245/832c3668-cffe-4b27-8b73-1dec09b9b5bc)

![Screenshot from 2024-01-11 12-40-29](https://github.com/techgebra/polosys-books/assets/138277245/2f6efd8b-cdea-4c2f-a916-49fb9a8180fd)

**Comment by saranya13-tech** [comment]
page reload issue

**Comment by AnjaliVellookkaran** [comment]
issue fixed !
