### ISSUE TITLE
login is happening when password field is entered along with white spaces 

### ISSUE THREAD

**Issue by AnjaliVellookkaran** [techgebra/polosys-books#73]
- [x] ![Screenshot from 2023-06-16 17-31-57](https://github.com/techgebra/polosys-books/assets/131741149/1e81bbee-4b10-43ee-bae9-c44f21999d93)

**Comment by MohdSahal** [comment]
@AnjaliVellookkaran please check and close

**Comment by AnjaliVellookkaran** [comment]
issue fixed
