### ISSUE TITLE
white spaces should not be engaged to enter in the username and password field during login 

### ISSUE THREAD

**Issue by AnjaliVellookkaran** [techgebra/polosys-books#74]

**Comment by MohdSahal** [comment]
@AnjaliVellookkaran please check and close

**Comment by AnjaliVellookkaran** [comment]
![Screenshot from 2023-07-05 15-39-09](https://github.com/techgebra/polosys-books/assets/131741149/b8717820-7094-4f16-9aea-3c37073b1d03)
email field accepts white spaces along with it

**Comment by MohdSahal** [comment]
Email field not done @zahidmuhammed @saranya13-tech

**Comment by AnjaliVellookkaran** [comment]
issue fixed!
