### ISSUE TITLE
issue in chart of account filter page

### ISSUE THREAD

**Issue by AnjaliVellookkaran** [techgebra/polosys-books#795]
- [x] advanced search and customize column icon issue
![Screenshot from 2024-02-05 15-05-45](https://github.com/techgebra/polosys-books/assets/131741149/55268cbb-9e43-4aa1-b94f-ffb32b7984cd)

**Comment by MohamedRoshanPU** [comment]
Please Check it with new organization

**Comment by AnjaliVellookkaran** [comment]
issue fixed !
