### ISSUE TITLE
Bills bugs

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books#88]
- [x] Amount paid column not able to enter amount
- [x] Mark fully paid function working even if credit transaction 
- [x] UI issue customer selection in bills creation screen
![image](https://github.com/techgebra/polosys-books/assets/132666132/58a3d076-9560-4864-8737-fffaae32e065)

- [x] Landed cost's amount shown sales rate instead of purchase rate.
- [x] Landed cost's headings are still there even after removing all line of services.
- [ ]

**Comment by avandhikaashokan** [comment]
bug fixed
