### ISSUE TITLE
ui change in bill field of vendor credits under purchase module

### ISSUE THREAD

**Issue by AnjaliVellookkaran** [techgebra/polosys-books#90]
![Screenshot from 2023-06-23 15-09-41](https://github.com/techgebra/polosys-books/assets/131741149/bacbce6a-b1ad-44bd-859f-c2875d51583e)

**Comment by MohdSahal** [comment]
@AnjaliVellookkaran please check and close

**Comment by AnjaliVellookkaran** [comment]
issue fixed
