### ISSUE TITLE
UI issue in inventory adjustment of item module

### ISSUE THREAD

**Issue by AnjaliVellookkaran** [techgebra/polosys-books#97]
- [x] ![Screenshot from 2023-06-26 13-47-29](https://github.com/techgebra/polosys-books/assets/131741149/a459f08d-d5a0-4ea6-b708-e3f6557e6e98)

**Comment by MohdSahal** [comment]
@AnjaliVellookkaran please check and close

**Comment by AnjaliVellookkaran** [comment]
issue solved
